### ISSUE TITLE
maru-0.7 does not contains any maru code

### ISSUE THREAD

**Issue by pintaf** [maruos/android_platform_frameworks_base#7]
Hello Preetam.

I discovered that branch maru-0.7 just contains LOS code and no maruos bits were added.
Is there any reason to that ?
For example no PerspectiveManager or anything.

**Comment by pdsouza** [comment]
I just didn't have the time to merge in any Maru code to base or native as I mentioned in https://github.com/maruos/maruos/issues/154#issuecomment-731866435.

I should have time to merge those in this weekend.

**Comment by pintaf** [comment]
Oh ok Thanks, I though everything was ready.
Neat if it can be done this week-end

**Comment by pintaf** [comment]
Oh ok Thanks, I though everything was ready.
Neat if it can be done this week-end :)
